### PR TITLE
Update to latest version of Apicurito

### PR DESCRIPTION
**Pull request by gayanper**

### CODE REVIEW

**Comment by gayanper** [comment]
> Thank you for this PR! Any chance you'd be willing to make the same changes here?:
> 
> https://github.com/Apicurio/apicurito/

Yes i can try and push in the next weekend

**Comment by EricWittmann** [comment]
On it.

**Comment by EricWittmann** [comment]
Ok I've updated node.js to version 16 (latest LTS) - can you rebase this PR so the workflow will re-run?

**Review by EricWittmann — APPROVED** [review]

**Comment by EricWittmann** [comment]
Awesome thanks!

**Pull request merged**
